name: Minecraft Geyser Server
version: "1.0.0"
slug: minecraft_geyser
description: Minecraft server supporting Java and Bedrock clients with whitelist and operator management
init: false
arch:
  - amd64
  - aarch64
  - armv7
ports:
  25565/tcp: 25565
  19132/udp: 19132
ports_description:
  25565/tcp: Minecraft Java Edition port
  19132/udp: Minecraft Bedrock Edition port
map:
  - addons:rw
options:
  EULA: true
  TYPE: PAPER
  PAPER_CHANNEL: default
  VERSION: "1.21.5"
  MOTD: "Welcome to our Minecraft Server!"
  MAX_PLAYERS: 20
  ONLINE_MODE: true
  ALLOW_FLIGHT: false
  DIFFICULTY: easy
  GAMEMODE: survival
  PLUGINS: https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
  WHITELIST: player1,player2
  EXISTING_WHITELIST_FILE: SYNCHRONIZE
  OPS: admin1,admin2
  EXISTING_OPS_FILE: SYNCHRONIZE
  USER_API_PROVIDER: mojang
schema:
  EULA: bool
  TYPE: str
  PAPER_CHANNEL: list(default|experimental)
  VERSION: str
  MOTD: str
  MAX_PLAYERS: int
  ONLINE_MODE: bool
  ALLOW_FLIGHT: bool
  DIFFICULTY: list(peaceful|easy|normal|hard)
  GAMEMODE: list(survival|creative|adventure|spectator)
  PLUGINS: str
  WHITELIST: str
  ENABLE_WHITELIST: bool?
  ENFORCE_WHITELIST: bool?
  EXISTING_WHITELIST_FILE: list(SKIP|SYNCHRONIZE|MERGE|SYNC_FILE_MERGE_LIST)
  USER_API_PROVIDER: list(playerdb|mojang)
  OPS: str
  EXISTING_OPS_FILE: list(SKIP|SYNCHRONIZE|MERGE|SYNC_FILE_MERGE_LIST)